### ISSUE TITLE
data for time series example

### ISSUE THREAD

**Issue by smsaladi** [vsmolyakov/experiments_with_python#3]
is this available somewhere to work with the notebook tutorial?

https://github.com/vsmolyakov/experiments_with_python/blob/master/chp01/keras_lstm_seqclass.ipynb

**Comment by vsmolyakov** [comment]
Yes! The data for the time-series notebook can be downloaded from:
http://www.cs.ucr.edu/~eamonn/time_series_data/
As the notebook mentions, the specific dataset used is: ECG5000.
